// Generated by Framer (890879b)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    RichText,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS,
    withFX,
    withOptimizedAppearEffect
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/8NyK0VaS6UEame5AosBV/T2xRUU8QDFccf1yiHy5y/StOoogDYM.js";
const MotionDivWithFX = withFX(motion.div);
const MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(withFX(motion.div));
const cycleOrder = ["kGThXGYYa", "VCCIFKCnt", "hFCaFlgb0"];
const serializationHash = "framer-gvLaL";
const variantClassNames = {
    hFCaFlgb0: "framer-v-t9iexr",
    kGThXGYYa: "framer-v-7hil2w",
    VCCIFKCnt: "framer-v-12r6kzm"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    duration: 0,
    type: "tween"
};
const transition2 = {
    delay: 0,
    duration: .3,
    ease: [.44, 0, .56, 1],
    type: "tween"
};
const animation = {
    opacity: 1,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    transition: transition2,
    x: 0,
    y: 0
};
const animation1 = {
    opacity: .001,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: 0
};
const transition3 = {
    delay: 0,
    duration: 1,
    ease: [0, 0, 1, 1],
    type: "tween"
};
const animation2 = {
    opacity: 1,
    rotate: 360,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: 0
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Default: "kGThXGYYa",
    Hidden: "hFCaFlgb0",
    Loading: "VCCIFKCnt"
};
const getProps = ({
    click,
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "kGThXGYYa",
        Wld3NDzSj: click ? ? props.Wld3NDzSj
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        Wld3NDzSj,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "kGThXGYYa",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTapn9xadi = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (Wld3NDzSj) {
            const res = await Wld3NDzSj(...args);
            if (res === false) return false;
        }
    });
    const sharedStyleClassNames = [sharedStyle.className];
    const isDisplayed = () => {
        if (baseVariant === "hFCaFlgb0") return false;
        return true;
    };
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed1 = () => {
        if (baseVariant === "VCCIFKCnt") return false;
        return true;
    };
    const isDisplayed2 = () => {
        if (baseVariant === "VCCIFKCnt") return true;
        return false;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: isDisplayed() && /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.button, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-7hil2w", className, classNames),
                    "data-framer-name": "Default",
                    "data-highlight": true,
                    "data-reset": "button",
                    layoutDependency: layoutDependency,
                    layoutId: "kGThXGYYa",
                    onTap: onTapn9xadi,
                    ref: refBinding,
                    style: {
                        backgroundColor: "var(--token-6396e7f2-0645-4f69-9a36-80e94f8ee015, rgb(0, 0, 0))",
                        borderBottomLeftRadius: 10,
                        borderBottomRightRadius: 10,
                        borderTopLeftRadius: 10,
                        borderTopRightRadius: 10,
                        boxShadow: "0px 0.6021873017743928px 1.083937143193907px -1.25px rgba(61, 61, 61, 0.72), 0px 2.288533303243457px 4.119359945838223px -2.5px rgba(61, 61, 61, 0.64), 0px 10px 18px -3.75px rgba(61, 61, 61, 0.25), 0px 0.7065919983928324px 0.7065919983928324px -0.5833333333333333px rgba(0, 0, 0, 0.35), 0px 1.8065619053231785px 1.8065619053231785px -1.1666666666666665px rgba(0, 0, 0, 0.34), 0px 3.6217592146567767px 3.6217592146567767px -1.75px rgba(0, 0, 0, 0.33), 0px 6.8655999097303715px 6.8655999097303715px -2.333333333333333px rgba(0, 0, 0, 0.3), 0px 13.646761411524492px 13.646761411524492px -2.916666666666667px rgba(0, 0, 0, 0.26), 0px 30px 30px -3.5px rgba(0, 0, 0, 0.15)",
                        ...style
                    },
                    ...addPropertyOverrides({
                        VCCIFKCnt: {
                            "data-framer-name": "Loading"
                        }
                    }, baseVariant, gestureVariant),
                    children: [isDisplayed1() && /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-12su4sl",
                                "data-styles-preset": "StOoogDYM",
                                children: "Load More"
                            })
                        }),
                        className: "framer-tycyfs",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "PfHGV2M6h",
                        verticalAlignment: "top",
                        withExternalLayout: true
                    }), isDisplayed2() && /*#__PURE__*/ _jsx(MotionDivWithFXWithOptimizedAppearEffect, {
                        __perspectiveFX: false,
                        __smartComponentFX: true,
                        __targetOpacity: 1,
                        animate: animation,
                        className: "framer-1uzyen0",
                        "data-framer-appear-id": "1uzyen0",
                        "data-framer-name": "Spinner",
                        initial: animation1,
                        layoutDependency: layoutDependency,
                        layoutId: "cnKMuUPkG",
                        optimized: true,
                        style: {
                            mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
                            WebkitMask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add"
                        },
                        children: /*#__PURE__*/ _jsx(MotionDivWithFX, {
                            __framer__loop: animation2,
                            __framer__loopEffectEnabled: true,
                            __framer__loopRepeatDelay: 0,
                            __framer__loopRepeatType: "loop",
                            __framer__loopTransition: transition3,
                            __perspectiveFX: false,
                            __smartComponentFX: true,
                            __targetOpacity: 1,
                            className: "framer-u05i53",
                            "data-framer-name": "Conic",
                            layoutDependency: layoutDependency,
                            layoutId: "kDdULlfFt",
                            style: {
                                background: "conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 0deg, rgb(255, 255, 255) 342deg)"
                            },
                            children: /*#__PURE__*/ _jsx(motion.div, {
                                className: "framer-1s23c04",
                                "data-framer-name": "Round",
                                layoutDependency: layoutDependency,
                                layoutId: "uSdyh1gqB",
                                style: {
                                    backgroundColor: "rgb(255, 255, 255)",
                                    borderBottomLeftRadius: 1,
                                    borderBottomRightRadius: 1,
                                    borderTopLeftRadius: 1,
                                    borderTopRightRadius: 1
                                }
                            })
                        })
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-gvLaL.framer-1ifr40e, .framer-gvLaL .framer-1ifr40e { display: block; }", ".framer-gvLaL.framer-7hil2w { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; padding: 12px 24px 12px 24px; position: relative; width: min-content; }", ".framer-gvLaL .framer-tycyfs { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }", ".framer-gvLaL .framer-1uzyen0 { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 20px); overflow: visible; position: relative; width: 20px; }", ".framer-gvLaL .framer-u05i53 { bottom: 0px; flex: none; gap: 10px; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }", ".framer-gvLaL .framer-1s23c04 { flex: none; height: 2px; left: calc(50.00000000000002% - 2px / 2); overflow: visible; position: absolute; top: 0px; width: 2px; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 46
 * @framerIntrinsicWidth 119
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"VCCIFKCnt":{"layout":["auto","auto"]},"hFCaFlgb0":{"layout":["auto","auto"]}}}
 * @framerVariables {"Wld3NDzSj":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const Framerxe_Xxhd2T = withCSS(Component, css, "framer-gvLaL");
export default Framerxe_Xxhd2T;
Framerxe_Xxhd2T.displayName = "Load More";
Framerxe_Xxhd2T.defaultProps = {
    height: 46,
    width: 119
};
addPropertyControls(Framerxe_Xxhd2T, {
    variant: {
        options: ["kGThXGYYa", "VCCIFKCnt", "hFCaFlgb0"],
        optionTitles: ["Default", "Loading", "Hidden"],
        title: "Variant",
        type: ControlType.Enum
    },
    Wld3NDzSj: {
        title: "Click",
        type: ControlType.EventHandler
    }
});
addFonts(Framerxe_Xxhd2T, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "Framerxe_Xxhd2T",
            "slots": [],
            "annotations": {
                "framerIntrinsicHeight": "46",
                "framerComponentViewportWidth": "true",
                "framerDisplayContentsDiv": "false",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"VCCIFKCnt\":{\"layout\":[\"auto\",\"auto\"]},\"hFCaFlgb0\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerColorSyntax": "true",
                "framerIntrinsicWidth": "119",
                "framerAutoSizeImages": "true",
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerVariables": "{\"Wld3NDzSj\":\"click\"}"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./xe_Xxhd2T.map