// Generated by Framer (8ebf084)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    ComponentViewportProvider,
    cx,
    getFonts,
    getFontsFromSharedStyle,
    Link,
    RichText,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import {
    Icon as Phosphor
} from "https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/p8dptk4UIND8hbFWz9V7/Phosphor.js";
import * as sharedStyle from "https://framerusercontent.com/modules/8NyK0VaS6UEame5AosBV/T2xRUU8QDFccf1yiHy5y/StOoogDYM.js";
const PhosphorFonts = getFonts(Phosphor);
const serializationHash = "framer-eB2dJ";
const variantClassNames = {
    Gj1MOkLWz: "framer-v-1gppf8s"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    damping: 60,
    delay: 0,
    mass: 1,
    stiffness: 500,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "Gj1MOkLWz",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: "https://framebase.lemonsqueezy.com/buy/ed1b4c3d-925c-4434-8a7f-de7f9cd40560",
                    motionChild: true,
                    nodeId: "Gj1MOkLWz",
                    openInNewTab: true,
                    scopeId: "n1lHEYpP8",
                    children: /*#__PURE__*/ _jsxs(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-1gppf8s",className,classNames)} framer-1ncd0be`,
                        "data-border": true,
                        "data-framer-name": "Variant 1",
                        layoutDependency: layoutDependency,
                        layoutId: "Gj1MOkLWz",
                        ref: refBinding,
                        style: {
                            "--border-bottom-width": "1px",
                            "--border-color": "var(--token-6396e7f2-0645-4f69-9a36-80e94f8ee015, rgb(14, 28, 41))",
                            "--border-left-width": "1px",
                            "--border-right-width": "1px",
                            "--border-style": "solid",
                            "--border-top-width": "1px",
                            background: "linear-gradient(180deg, rgba(62, 105, 184, 0.5) 0%, var(--token-6396e7f2-0645-4f69-9a36-80e94f8ee015, rgb(14, 28, 41)) 16.216216216216218%)",
                            borderBottomLeftRadius: 11,
                            borderBottomRightRadius: 11,
                            borderTopLeftRadius: 11,
                            borderTopRightRadius: 11,
                            boxShadow: "0px 0.6021873017743928px 1.083937143193907px -1.25px rgba(61, 61, 61, 0.72), 0px 2.288533303243457px 4.119359945838223px -2.5px rgba(61, 61, 61, 0.64), 0px 10px 18px -3.75px rgba(61, 61, 61, 0.25), 0px 0.7065919983928324px 0.7065919983928324px -0.5833333333333333px rgba(0, 0, 0, 0.35), 0px 1.8065619053231785px 1.8065619053231785px -1.1666666666666665px rgba(0, 0, 0, 0.34), 0px 3.6217592146567767px 3.6217592146567767px -1.75px rgba(0, 0, 0, 0.33), 0px 6.8655999097303715px 6.8655999097303715px -2.333333333333333px rgba(0, 0, 0, 0.3), 0px 13.646761411524492px 13.646761411524492px -2.916666666666667px rgba(0, 0, 0, 0.26), 0px 30px 30px -3.5px rgba(0, 0, 0, 0.15)",
                            ...style
                        },
                        children: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-14sbuos-container",
                                isAuthoredByUser: true,
                                isModuleExternal: true,
                                layoutDependency: layoutDependency,
                                layoutId: "QxpqawPLR-container",
                                nodeId: "QxpqawPLR",
                                rendersWithMotion: true,
                                scopeId: "n1lHEYpP8",
                                children: /*#__PURE__*/ _jsx(Phosphor, {
                                    color: "var(--token-d4c0a0e6-8fba-45bc-8f6f-215e608cd0df, rgb(255, 255, 255))",
                                    height: "100%",
                                    iconSearch: "House",
                                    iconSelection: "Command",
                                    id: "QxpqawPLR",
                                    layoutId: "QxpqawPLR",
                                    mirrored: false,
                                    selectByList: true,
                                    style: {
                                        height: "100%",
                                        width: "100%"
                                    },
                                    weight: "duotone",
                                    width: "100%"
                                })
                            })
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-12su4sl",
                                    "data-styles-preset": "StOoogDYM",
                                    children: "Get Orb AI"
                                })
                            }),
                            className: "framer-3qnmqr",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "S7cgqHiN3",
                            style: {
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline",
                                "--framer-paragraph-spacing": "0px"
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-eB2dJ.framer-1ncd0be, .framer-eB2dJ .framer-1ncd0be { display: block; }", ".framer-eB2dJ.framer-1gppf8s { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 7px; height: min-content; justify-content: center; overflow: hidden; padding: 8px 14px 8px 12px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }", ".framer-eB2dJ .framer-14sbuos-container { flex: none; height: 18px; position: relative; width: 18px; }", ".framer-eB2dJ .framer-3qnmqr { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ...sharedStyle.css, '.framer-eB2dJ[data-border="true"]::after, .framer-eB2dJ [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 38.5
 * @framerIntrinsicWidth 120.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const Framern1lHEYpP8 = withCSS(Component, css, "framer-eB2dJ");
export default Framern1lHEYpP8;
Framern1lHEYpP8.displayName = "Get template (can delete this)";
Framern1lHEYpP8.defaultProps = {
    height: 38.5,
    width: 120.5
};
addFonts(Framern1lHEYpP8, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...PhosphorFonts, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "Framern1lHEYpP8",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerIntrinsicHeight": "38.5",
                "framerComponentViewportWidth": "true",
                "framerIntrinsicWidth": "120.5",
                "framerAutoSizeImages": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerImmutableVariables": "true",
                "framerColorSyntax": "true",
                "framerDisplayContentsDiv": "false"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./n1lHEYpP8.map