// Generated by Framer (dc5e905)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    getFontsFromSharedStyle,
    getPropertyControls,
    Link,
    RichText,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import {
    Icon as Phosphor
} from "https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/p8dptk4UIND8hbFWz9V7/Phosphor.js";
import * as sharedStyle from "https://framerusercontent.com/modules/u02VmHOxLhvzU9MnPvJn/ckZWF7MqQLlxcS6fRNUf/cH8AiB6P_.js";
import * as sharedStyle1 from "https://framerusercontent.com/modules/slLGb1hjMMEbsAfxk0Y7/L06yUo3kT2o5asZLfrGZ/CO_HimyHZ.js";
const PhosphorFonts = getFonts(Phosphor);
const PhosphorControls = getPropertyControls(Phosphor);
const serializationHash = "framer-DYEXq";
const variantClassNames = {
    TU2y4Fak3: "framer-v-15b2alo"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    description,
    height,
    iconName,
    id,
    link,
    linkText,
    width,
    ...props
}) => {
    return { ...props,
        mMVNKlGDF: description ? ? props.mMVNKlGDF ? ? "Facing technical challenges or product concerns? We’re here to assist",
        rP8Jq5Q0s: link ? ? props.rP8Jq5Q0s,
        TLJ29SMlg: linkText ? ? props.TLJ29SMlg ? ? "orbai@support.com",
        zGjvMvORl: iconName ? ? props.zGjvMvORl ? ? "EnvelopeSimple"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        zGjvMvORl,
        mMVNKlGDF,
        TLJ29SMlg,
        rP8Jq5Q0s,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "TU2y4Fak3",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-15b2alo", className, classNames),
                    "data-framer-name": "primary",
                    layoutDependency: layoutDependency,
                    layoutId: "TU2y4Fak3",
                    ref: refBinding,
                    style: {
                        backgroundColor: "var(--token-4f00a517-d75a-4557-9433-caf4536a911d, rgb(245, 245, 245))",
                        borderBottomLeftRadius: 16,
                        borderBottomRightRadius: 16,
                        borderTopLeftRadius: 16,
                        borderTopRightRadius: 16,
                        boxShadow: "0px 0.7065919983928324px 0.7065919983928324px -0.6666666666666666px rgba(0, 0, 0, 0.08), 0px 1.8065619053231785px 1.8065619053231785px -1.3333333333333333px rgba(0, 0, 0, 0.08), 0px 3.6217592146567767px 3.6217592146567767px -2px rgba(0, 0, 0, 0.07), 0px 6.8655999097303715px 6.8655999097303715px -2.6666666666666665px rgba(0, 0, 0, 0.07), 0px 13.646761411524492px 13.646761411524492px -3.3333333333333335px rgba(0, 0, 0, 0.05), 0px 30px 30px -4px rgba(0, 0, 0, 0.02), inset 0px 3px 1px 0px rgb(255, 255, 255)",
                        ...style
                    },
                    children: /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-nh2l6z",
                        "data-framer-name": "content",
                        layoutDependency: layoutDependency,
                        layoutId: "fbKrdVFZk",
                        children: [ /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-wyi9je",
                            "data-framer-name": "icon&text",
                            layoutDependency: layoutDependency,
                            layoutId: "VtxpICenG",
                            children: /*#__PURE__*/ _jsx(motion.div, {
                                className: "framer-1bupfp1",
                                "data-framer-name": "icon",
                                layoutDependency: layoutDependency,
                                layoutId: "blH243NFP",
                                style: {
                                    background: "linear-gradient(180deg, var(--token-6396e7f2-0645-4f69-9a36-80e94f8ee015, rgb(0, 0, 0)) 0%, var(--token-d4c0a0e6-8fba-45bc-8f6f-215e608cd0df, rgb(255, 255, 255)) 170%)",
                                    borderBottomLeftRadius: 10,
                                    borderBottomRightRadius: 10,
                                    borderTopLeftRadius: 10,
                                    borderTopRightRadius: 10,
                                    boxShadow: "0px 0.7065919983928324px 0.7065919983928324px -0.5416666666666666px rgba(171, 171, 171, 0.64), 0px 1.8065619053231785px 1.8065619053231785px -1.0833333333333333px rgba(171, 171, 171, 0.63), 0px 3.6217592146567767px 3.6217592146567767px -1.625px rgba(171, 171, 171, 0.61), 0px 6.8655999097303715px 6.8655999097303715px -2.1666666666666665px rgba(171, 171, 171, 0.58), 0px 13.646761411524492px 13.646761411524492px -2.7083333333333335px rgba(171, 171, 171, 0.51), 0px 30px 30px -3.25px rgba(171, 171, 171, 0.35)"
                                },
                                children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-1x9nned-container",
                                        isAuthoredByUser: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "b_MXzB7V6-container",
                                        nodeId: "b_MXzB7V6",
                                        rendersWithMotion: true,
                                        scopeId: "hEdNIyT89",
                                        children: /*#__PURE__*/ _jsx(Phosphor, {
                                            color: "var(--token-d4c0a0e6-8fba-45bc-8f6f-215e608cd0df, rgb(255, 255, 255))",
                                            height: "100%",
                                            iconSearch: "House",
                                            iconSelection: zGjvMvORl,
                                            id: "b_MXzB7V6",
                                            layoutId: "b_MXzB7V6",
                                            mirrored: false,
                                            selectByList: true,
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            weight: "regular",
                                            width: "100%"
                                        })
                                    })
                                })
                            })
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-1khckfh",
                                    "data-styles-preset": "cH8AiB6P_",
                                    style: {
                                        "--framer-text-alignment": "left"
                                    },
                                    children: "Facing technical challenges or product concerns? We’re here to assist"
                                })
                            }),
                            className: "framer-1bjuyb0",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "csD7oo_EQ",
                            style: {
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline",
                                opacity: .8
                            },
                            text: mMVNKlGDF,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-1khckfh",
                                    "data-styles-preset": "cH8AiB6P_",
                                    style: {
                                        "--framer-text-alignment": "left"
                                    },
                                    children: /*#__PURE__*/ _jsx(Link, {
                                        href: rP8Jq5Q0s,
                                        motionChild: true,
                                        nodeId: "cVteodnyh",
                                        openInNewTab: true,
                                        scopeId: "hEdNIyT89",
                                        smoothScroll: false,
                                        children: /*#__PURE__*/ _jsx(motion.a, {
                                            className: "framer-styles-preset-1snln9b",
                                            "data-styles-preset": "CO_HimyHZ",
                                            children: "orbai@support.com"
                                        })
                                    })
                                })
                            }),
                            className: "framer-9xv27w",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "cVteodnyh",
                            text: TLJ29SMlg,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-DYEXq.framer-m8gi6h, .framer-DYEXq .framer-m8gi6h { display: block; }", ".framer-DYEXq.framer-15b2alo { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: hidden; padding: 32px; position: relative; width: 452px; will-change: var(--framer-will-change-override, transform); }", ".framer-DYEXq .framer-nh2l6z { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }", ".framer-DYEXq .framer-wyi9je { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }", ".framer-DYEXq .framer-1bupfp1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 8px 10px 8px 10px; position: relative; width: min-content; }", ".framer-DYEXq .framer-1x9nned-container { flex: none; height: 32px; position: relative; width: 32px; }", ".framer-DYEXq .framer-1bjuyb0, .framer-DYEXq .framer-9xv27w { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }", ...sharedStyle.css, ...sharedStyle1.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 216
 * @framerIntrinsicWidth 452
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}
 * @framerVariables {"zGjvMvORl":"iconName","mMVNKlGDF":"description","TLJ29SMlg":"linkText","rP8Jq5Q0s":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerhEdNIyT89 = withCSS(Component, css, "framer-DYEXq");
export default FramerhEdNIyT89;
FramerhEdNIyT89.displayName = "contact card";
FramerhEdNIyT89.defaultProps = {
    height: 216,
    width: 452
};
addPropertyControls(FramerhEdNIyT89, {
    zGjvMvORl: PhosphorControls ? .["iconSelection"] && { ...PhosphorControls["iconSelection"],
        defaultValue: "EnvelopeSimple",
        description: undefined,
        hidden: undefined,
        title: "Icon Name"
    },
    mMVNKlGDF: {
        defaultValue: "Facing technical challenges or product concerns? We’re here to assist",
        displayTextArea: false,
        title: "Description",
        type: ControlType.String
    },
    TLJ29SMlg: {
        defaultValue: "orbai@support.com",
        displayTextArea: false,
        title: "Link text",
        type: ControlType.String
    },
    rP8Jq5Q0s: {
        title: "Link",
        type: ControlType.Link
    }
});
addFonts(FramerhEdNIyT89, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...PhosphorFonts, ...getFontsFromSharedStyle(sharedStyle.fonts), ...getFontsFromSharedStyle(sharedStyle1.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerhEdNIyT89",
            "slots": [],
            "annotations": {
                "framerIntrinsicHeight": "216",
                "framerComponentViewportWidth": "true",
                "framerColorSyntax": "true",
                "framerImmutableVariables": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerIntrinsicWidth": "452",
                "framerDisplayContentsDiv": "false",
                "framerVariables": "{\"zGjvMvORl\":\"iconName\",\"mMVNKlGDF\":\"description\",\"TLJ29SMlg\":\"linkText\",\"rP8Jq5Q0s\":\"link\"}",
                "framerAutoSizeImages": "true",
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}