// Generated by Framer (53c1d35)
export default function metadata(params, activeLocale) {
    return {
        description: "Orbai is a premium Framer template built to elevate your AI automation agency. Designed with a sleek, modern aesthetic.",
        favicon: "https://framerusercontent.com/assets/ODgTo7CT2KtJQ2CuhSdG28DskhE.png",
        robots: "max-image-preview:large",
        socialImage: "https://framerusercontent.com/assets/jV4ovNxnxoMkGdrGCld0sylE1U.png",
        title: "Orbai – AI Agency Template"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}