// Generated by Framer (2306ade)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const cycleOrder = ["BzUKvPRzb", "MM1Hh5nwG"];
const serializationHash = "framer-IygxY";
const variantClassNames = {
    BzUKvPRzb: "framer-v-euwp3t",
    MM1Hh5nwG: "framer-v-qtwiys"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    damping: 30,
    delay: 0,
    mass: 1,
    stiffness: 400,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Burger: "BzUKvPRzb",
    X: "MM1Hh5nwG"
};
const getProps = ({
    height,
    id,
    tap,
    width,
    ...props
}) => {
    return { ...props,
        TBgHLr7MW: tap ? ? props.TBgHLr7MW,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "BzUKvPRzb"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        TBgHLr7MW,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "BzUKvPRzb",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTapb0a6uq = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (TBgHLr7MW) {
            const res = await TBgHLr7MW(...args);
            if (res === false) return false;
        }
        setVariant("MM1Hh5nwG");
    });
    const onTap1iqprg = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (TBgHLr7MW) {
            const res = await TBgHLr7MW(...args);
            if (res === false) return false;
        }
        setVariant("BzUKvPRzb");
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-euwp3t", className, classNames),
                    "data-framer-name": "Burger",
                    "data-highlight": true,
                    layoutDependency: layoutDependency,
                    layoutId: "BzUKvPRzb",
                    onTap: onTapb0a6uq,
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        MM1Hh5nwG: {
                            "data-framer-name": "X",
                            onTap: onTap1iqprg
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-ndj8g4",
                        "data-framer-name": "hamburger menu",
                        layoutDependency: layoutDependency,
                        layoutId: "P1aXGNvqJ",
                        children: [ /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-s1s6j8",
                            "data-framer-name": "Bottom",
                            layoutDependency: layoutDependency,
                            layoutId: "z8OYTK7qG",
                            style: {
                                backgroundColor: "var(--token-6396e7f2-0645-4f69-9a36-80e94f8ee015, rgb(0, 0, 0))",
                                rotate: 0
                            },
                            variants: {
                                MM1Hh5nwG: {
                                    rotate: -45
                                }
                            }
                        }), /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-upby0b",
                            "data-framer-name": "Mid",
                            layoutDependency: layoutDependency,
                            layoutId: "Z41tT89B1",
                            style: {
                                backgroundColor: "var(--token-6396e7f2-0645-4f69-9a36-80e94f8ee015, rgb(0, 0, 0))",
                                opacity: 1
                            },
                            variants: {
                                MM1Hh5nwG: {
                                    opacity: 0
                                }
                            }
                        }), /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-r6f99x",
                            "data-framer-name": "Top",
                            layoutDependency: layoutDependency,
                            layoutId: "T3oepJWFp",
                            style: {
                                backgroundColor: "var(--token-6396e7f2-0645-4f69-9a36-80e94f8ee015, rgb(0, 0, 0))",
                                rotate: 0
                            },
                            variants: {
                                MM1Hh5nwG: {
                                    rotate: 45
                                }
                            }
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-IygxY.framer-9rmfvx, .framer-IygxY .framer-9rmfvx { display: block; }", ".framer-IygxY.framer-euwp3t { cursor: pointer; height: 32px; overflow: hidden; position: relative; width: 32px; }", ".framer-IygxY .framer-ndj8g4 { flex: none; height: 18px; left: calc(50.00000000000002% - 24px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 18px / 2); width: 24px; }", ".framer-IygxY .framer-s1s6j8 { bottom: 0px; flex: none; height: 2px; left: 0px; overflow: hidden; position: absolute; right: 0px; }", ".framer-IygxY .framer-upby0b { flex: none; height: 2px; left: 0px; overflow: hidden; position: absolute; right: 0px; top: calc(50.00000000000002% - 2px / 2); }", ".framer-IygxY .framer-r6f99x { flex: none; height: 2px; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; }", ".framer-IygxY.framer-v-qtwiys .framer-s1s6j8 { bottom: unset; top: calc(50.00000000000002% - 2px / 2); }", ".framer-IygxY.framer-v-qtwiys .framer-upby0b { left: unset; width: 2px; }", ".framer-IygxY.framer-v-qtwiys .framer-r6f99x { left: unset; right: -1px; top: calc(50.00000000000002% - 2px / 2); width: 26px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 32
 * @framerIntrinsicWidth 32
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"MM1Hh5nwG":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"TBgHLr7MW":"tap"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramercXGwRnQ5A = withCSS(Component, css, "framer-IygxY");
export default FramercXGwRnQ5A;
FramercXGwRnQ5A.displayName = "nav / Menu Icon";
FramercXGwRnQ5A.defaultProps = {
    height: 32,
    width: 32
};
addPropertyControls(FramercXGwRnQ5A, {
    variant: {
        options: ["BzUKvPRzb", "MM1Hh5nwG"],
        optionTitles: ["Burger", "X"],
        title: "Variant",
        type: ControlType.Enum
    },
    TBgHLr7MW: {
        title: "Tap",
        type: ControlType.EventHandler
    }
});
addFonts(FramercXGwRnQ5A, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramercXGwRnQ5A",
            "slots": [],
            "annotations": {
                "framerVariables": "{\"TBgHLr7MW\":\"tap\"}",
                "framerComponentViewportWidth": "true",
                "framerImmutableVariables": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"MM1Hh5nwG\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerDisplayContentsDiv": "false",
                "framerAutoSizeImages": "true",
                "framerContractVersion": "1",
                "framerIntrinsicWidth": "32",
                "framerColorSyntax": "true",
                "framerIntrinsicHeight": "32"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./cXGwRnQ5A.map